apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: ocean
spec:
  selector:
    matchLabels:
      app: ocean
  replicas: 1
  template:
    metadata:
      labels:
        app: ocean
    spec:
      containers:
      - name: ocean
        image: ocean
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
  strategy:
    canary:
      canaryService: ocean-canary-svc
      stableService: ocean-svc
      trafficRouting:
        istio:
          virtualService:
            name: ocean-routing
            routes:
            - primary
      steps:
      - setWeight: 0
      - pause: {}