apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: fish
spec:
  selector:
    matchLabels:
      app: fish
  replicas: 2
  template:
    metadata:
      labels:
        app: fish
    spec:
      containers:
      - name: fish
        image: fish
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
  strategy:
    canary:
      canaryService: fish-canary-svc
      stableService: fish-svc
      trafficRouting:
        istio:
          virtualService: 
            name: fish-routing
            routes:
            - primary
      steps:
      - setWeight: 0
      # Force one pod to be spun up for dark releasing.
      - setCanaryScale:
          replicas: 1
      - pause: {}
      - setWeight: 5
      - pause: {}
      - setWeight: 15
      - pause: {}
      - setWeight: 35
      - pause: {}
      - setWeight: 65
      - pause: {}

